### ISSUE TITLE
Safelist Updater cant upload ISO file more than 4GB

### ISSUE THREAD

**Issue by adib0u** [CybercentreCanada/assemblyline-service-safelist#15]
I add the file "RDS_legacy.iso" to update the Safelist signature base but I have an error : 

`{"@timestamp": "2022-12-08 20:34:17,595", "event": { "module": "assemblyline", "dataset": "assemblyline.updater.safelist" }, "host": { "ip": "10.233.67.207", "hostname": "alsvc-safelist-updates-54fb6cf954-sm5z8" }, "log": { "level": "ERROR", "logger": "assemblyline.updater.safelist" }, "process": { "pid": "1" }, "message": "An error occurred running the update. Will retry...\nTraceback (most recent call last):\n File \"/var/lib/assemblyline/.local/lib/python3.9/site-packages/assemblyline_v4_service/updater/updater.py\", line 426, in _run_source_updates\n self.do_source_update(service=service)\n File \"/opt/al_service/update_server.py\", line 204, in do_source_update\n download_extract_iso(self.log, source, target_path,\n File \"/opt/al_service/update_server.py\", line 126, in download_extract_iso\n with zipfile.ZipFile(zip_file) as z:\n File \"/usr/local/lib/python3.9/zipfile.py\", line 1266, in __init__\n self._RealGetContents()\n File \"/usr/local/lib/python3.9/zipfile.py\", line 1333, in _RealGetContents\n raise BadZipFile(\"File is not a zip file\")\nzipfile.BadZipFile: File is not a zip file\n"}`

Then the update consider that the base is up to date when retrying with the same file but there is no signature in the signatures base.

I think there is a problem when using the lib [pycdlib](https://github.com/CybercentreCanada/assemblyline-service-safelist/blob/master/update_server.py#L117) to extract ISO file because this package use a ISO standard that specify ISO file cant be more than 4GB.

**Comment by cccs-rs** [comment]
This should be resolves in 4.3.1.stable5
